; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
upload_speed =921600 
upload_flags = 
    --before=default_reset
    --after=hard_reset
lib_deps = 
    adafruit/DHT sensor library @ ^1.4.7
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    mathworks/ThingSpeak @ ^2.0.0
    bblanchon/ArduinoJson @ ^6.21.4

; Opciones de compilación
build_flags = 
    -DCORE_DEBUG_LEVEL=0

; Monitor serie
monitor_filters = 
    esp32_exception_decoder
    time